### ISSUE TITLE
Improvement needed near country borders and water bodies

### ISSUE THREAD

**Issue by cgendreau** [gbif/geocode#1]
This issue is mostly a copy of POR-1387. The main purpose if to collect records that could be use to test and improve the reverse geocode ws.

Examples of a records incorrectly receiving a flag of "country coordinate mismatch":

Border issues:
http://www.gbif.org/occurrence/217745359

Water body issues:
http://www.gbif.org/occurrence/1212484753

**Comment by cgendreau** [comment]
No apprent issues:

**Comment by MattBlissett** [comment]
Fixed, see https://github.com/gbif/portal-feedback/issues/340
