### ISSUE TITLE
Topology issue with a lake in Denmark

### ISSUE THREAD

**Issue by leo-buitrago** [gbif/geocode#12]
Neither GADM nor Natural Earth includes the fjord in Denmark, and Marine Regions excludes it, so records like this https://www.gbif.org/occurrence/1993109931 will be reported as an issue if are located in that area https://www.gbif.org/occurrence/map?country=DK&issue=COUNTRY_COORDINATE_MISMATCH&geometry=POLYGON((10.34912%2058.11768,9.85474%2058.07373,9.49219%2057.67822,7.05322%2057.052,4.54834%2056.19507,5.55908%2055.65674,7.84424%2055.26123,9.12964%2055.14038,10.88745%2054.74487,12.40356%2054.60205,12.76611%2055.65674,11.84326%2056.75537,10.34912%2058.11768)). 
![image_2020_09_03T14_24_30_594Z](https://user-images.githubusercontent.com/61566113/92235753-83253880-eeb4-11ea-8164-64b7b6a4e591.png)

**Comment by MattBlissett** [comment]
A similar issue in Russia, near the Caspian Sea:

![image](https://user-images.githubusercontent.com/583320/135830189-113e3f96-2119-4e18-88b1-d4287b97e5ea.png)

Results in incorrect interpretation for this record: https://www.gbif.org/occurrence/2883444510

**Comment by MattBlissett** [comment]
Related, an inaccurate polygon for Nigeria: https://www.gbif.org/occurrence/search?dataset_key=ae857486-36ca-4669-9c7f-1d3aab6d2ce2&issue=PRESUMED_SWAPPED_COORDINATE

**Comment by MattBlissett** [comment]
This is fixed by using a combined Political + EEZ layer, rather than two separate layers.
