### ISSUE TITLE
Distance order is not preserved

### ISSUE THREAD

**Issue by timrobertson100** [gbif/geocode#17]
The geocode service is not preserving the ordering by distance.

This shows the problem.
```
SELECT layer, id, distance FROM query_layers(4.02, 50.02, 0.05, ARRAY['IHO', 'EEZ', 'Political', 'GADM1', 'GADM2', 'GADM3', 'Centroids', 'WGSRPD']);
   layer   │      id       │      distance
───────────┼───────────────┼────────────────────
 Political │ FR            │                  0
 GADM3     │ FRA.7.2.1_1   │                  0
 GADM2     │ FRA.7.2_1     │                  0
 GADM1     │ FRA.7_1       │                  0
 GADM3     │ FRA.7.1.5_1   │ 0.0261643707422069
 GADM2     │ FRA.7.1_1     │ 0.0261643707422069
 WGSRPD    │ WGSRPD:FRA-FR │                  0
```

We need to add `ORDER BY distance` to the Mapper SQL [here](https://github.com/gbif/geocode/blob/master/geocode-ws/src/main/resources/org/gbif/geocode/ws/persistence/mapper/LocationMapper.xml) and all the references to `Collection` should be replaced by `List` in the code relating to this (the service API, implementation, and WS resource)

**Comment by MattBlissett** [comment]
Collections replaced by Lists
