### ISSUE TITLE
Add gadm.org

### ISSUE THREAD

**Issue by timrobertson100** [gbif/geocode#6]
We wish to enable search by gadm regions in GBIF.org, which will need us to to provide a lookup service as a start.

**Comment by tucotuco** [comment]
How can I help?

**Comment by MattBlissett** [comment]
So far, I've changed geocode to add additional layers for GADM: https://api.gbif-uat.org/v1/geocode/reverse?lat=48.17156&lng=1.18177

Something you almost certainly know better than me — are there already terms for GADM identifiers?  I found http://linkedgeodata.org/GADM and http://gadm.geovocab.org/, but I don't know if these projects are used. They do not seem to have many updates.

**Comment by tucotuco** [comment]
I would not use either of those sources for identifiers for GADM. Both are out of date and have nothing to do with the identifiers that GADM provides internally, which are meant to be persistent as of version 3.6. You can find the explanantion of the identification system for GAM at https://gadm.org/metadata.html under the heading "An important note on IDs".

**Comment by MattBlissett** [comment]
This is ready in UAT, e.g. http://api.gbif-uat.org/v1/geocode/reverse?lng=1.900278&lat=41.338055
