### ISSUE TITLE
Migrate geocode to SpringBoot and fasterxml.jackson

### ISSUE THREAD

**Issue by fmendezh** [gbif/geocode#7]
The geocode service must be migrated to SpringBoot, this aims to bring consistency among all the frameworks and libraries used by the GBIF services. The following is a list of consideration that must be taken into consideration:

- Please create separate branch for this to avoid any conflict with the work that @MattBlissett is doing at this moment
- Use the GBIF latest motherpom version (at this moment  registry and occurrence use version 47)
- Upgrade all GBIF dependencies to the latest release version (api, common, common-ws, etc)
- Upgrade Jackson version to 2.10.3
- Remove all Jersey and Guice code and dependencies (minimize the use of Guava is a plus!)
- Migrate geocode-ws to use SpringBoot, use as reference the registry-ws or occurrence-ws projects
- Migrate geocode-ws-client to use io.github.openfeign, use the registry-ws-client and occurrence-ws-client as reference
- Migrate all Unit tests to use Junit5 (Jupiter), see examples in occurrence and registry project (this task is optional if it requires a huge effort of using incompatible libraries for _mocks_ )
- Update all required artifacts in the gbif-configuration project 
    - environment files that need be changed: services.yaml and monitoring.yml (change the expected response status from 200 OK to 200)
  - Service configuration for each environment: application.yml and bootstrap.yml

**Comment by mike-podolskiy90** [comment]
Branch spring-boot

**Comment by asturcon** [comment]
@mike-podolskiy90 I was already working on another branch (it's not pushed yet though)

**Comment by mike-podolskiy90** [comment]
I deleted those branch

**Comment by MattBlissett** [comment]
I've finished what I want to do with the geocoder, so this branch can be merged into master, preferably as a squash commit, `git merge --squash origin/spring-boot-migration`.  It's then ready for release.

The prod_eez database (as well as uat_eez and dev_eez) contains the newest data.

**Comment by marcos-lg** [comment]
It's merged and deployed in DEV. It seems stable but it would be good if you @MattBlissett can do a quick round of testing. Also, it'd be helpful if you could test the DockerFile too.

**Comment by MattBlissett** [comment]
Regenerating cache bitmaps no longer works, as it can't initialize without them:

```
rm ./geocode-ws/src/main/resources/org/gbif/geocode/ws/layers/wgsrpd.png
rm ./geocode-ws/src/main/resources/org/gbif/geocode/ws/resource/cache-bitmap.png
mvn clean install -DskipTests -Pdev
```

But otherwise I think all is fine.

**Comment by marcos-lg** [comment]
I just pushed a fix for that.

**Comment by MattBlissett** [comment]
That now works, although I was unable to release the project.

**Comment by marcos-lg** [comment]
The release is fixed now. I had to create many unnecessary releases to test the problem with the empty snapshots and hence the commit history got a bit dirty.

I think the only thing missing now is the config to deploy in UAT and PROD. We can create them when we're planning to deploy it.

**Comment by MattBlissett** [comment]
Thanks, that's great. I've tidied up the mess, by branching from just before what was geocode-0.16, squash-merging all the changes to the POM, and releasing.  I've removed all the test tags from Git, and all the test releases from Nexus.

You will need to "git reset" to get onto the new master branch, or else re-clone.
